from user.models import Menu, Privilege
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "menus setup"

    def handle(self, *args, **options):

        menus = [
            {
                "name": "Dashboard",
                "name_np": "ड्यासबोर्ड",
                "code": "internal_dashboard",
                "url": "/",
                "user_type": "1",
                "icon": "dashboard",
            },
            {
                "name": "Base Configuration",
                "name_np": "बेस कन्फिगरेसन",
                "code": "base_config",
                "url": "/base-config",
                "user_type": "1",
                "icon": "base_config",
            },
            {
                "name": "Psychometric Test",
                "name_np": "साइकोमेट्रिक परिक्षण",
                "code": "psychometric_test",
                "url": "/psychometric-test",
                "user_type": "1",
                "icon": "psychometric_test",
            },
            {
                "name": "Master Configuration",
                "name_np": "मास्टर कन्फिगरेसन",
                "code": "master_configuration",
                "url": "/master",
                "user_type": "1",
                "icon": "master",
            },
            {
                "name": "Branch Setup",
                "name_np": "साखा सेटअप",
                "code": "branch_setup",
                "parent": "master_configuration",
                "url": "/master/branch-setup",
                "user_type": "1",
            },
            {
                "name": "Province Setup",
                "name_np": "प्रदेश सेटअप",
                "code": "province_setup",
                "parent": "master_configuration",
                "url": "/master/province-setup",
                "user_type": "1",
            },
            {
                "name": "Loan Type",
                "name_np": "ऋण प्रकार",
                "code": "loan_type",
                "parent": "master_configuration",
                "url": "/master/loan-type",
                "user_type": "1",
            },
            {
                "name": "Loan Category",
                "name_np": "ऋण वर्ग",
                "code": "loan_category",
                "parent": "master_configuration",
                "url": "/master/loan-category",
            },
            {
                "name": "Designation",
                "name_np": "पद",
                "code": "designation",
                "parent": "master_configuration",
                "url": "/master/designation",
                "user_type": "1",
            },
            {
                "name": "Department",
                "name_np": "विभाग",
                "code": "department",
                "parent": "master_configuration",
                "url": "/master/department",
                "user_type": "1",
            },
            {
                "name": "Occupation",
                "name_np": "पेशा",
                "code": "occupation",
                "parent": "master_configuration",
                "url": "/master/occupation",
                "user_type": "1",
            },
            {
                "name": "Self Employment",
                "name_np": "स्वरोजगार",
                "code": "self_employment",
                "parent": "master_configuration",
                "url": "/master/self-employment",
                "user_type": "1",
            },
            {
                "name": "Assign Office",
                "name_np": "कार्यालय आवंटन",
                "code": "assign_office",
                "parent": "master_configuration",
                "url": "/master/assign-office",
                "user_type": "1",
            },
            {
                "name": "Eligibilty Criteria",
                "name_np": "योग्यता मापदण्ड",
                "code": "eligibility_criteria",
                "parent": "master_configuration",
                "url": "/master/eligibility-criteria",
                "user_type": "1",
            },
            {
                "name": "Fiscal Year",
                "name_np": "वित्तीय वर्ष",
                "code": "fiscal_year",
                "parent": "master_configuration",
                "url": "/master/fiscal-year",
                "user_type": "1",
            },
            {
                "name": "Declaration Setup",
                "name_np": "घोषणा सेटअप",
                "code": "declaration_setup",
                "parent": "master_configuration",
                "url": "/master/declaration-setup",
                "user_type": "1",
            },
            {
                "name": "Psychometric Config",
                "name_np": "साइकोमेट्रिक कन्फिगरेसन",
                "code": "psychometric_config",
                "parent": "master_configuration",
                "url": "/master/psychometric-config",
                "user_type": "1",
            },
            {
                "name": "User Management",
                "name_np": "प्रयोगकर्ता व्यवस्थापन",
                "code": "user_management",
                "url": "/user",
                "user_type": "1",
                "icon": "user",
            },
            {
                "name": "Users",
                "name_np": "प्रयोगकर्ताहरू",
                "code": "users",
                "parent": "user_management",
                "url": "/user/internal",
                "user_type": "1",
            },
            {
                "name": "User Activity Logs",
                "name_np": "प्रयोगकर्ता गतिविधि लगहरू",
                "code": "user_activity_logs",
                "parent": "user_management",
                "url": "/user/activity-logs",
                "user_type": "1",
            },
            {
                "name": "Customer List",
                "name_np": "ग्राहक सूची",
                "code": "customer_list",
                "parent": "user_management",
                "url": "/user/customer-list",
                "user_type": "1",
            },
            {
                "name": "Role Management",
                "name_np": "भूमिका व्यवस्थापन",
                "code": "role_management",
                "url": "/role-management",
                "user_type": "1",
                "icon": "role",
            },
            {
                "name": "Roles",
                "name_np": "भूमिकाहरू",
                "code": "roles",
                "parent": "role_management",
                "url": "/role-management/roles",
                "user_type": "1",
            },
            {
                "name": "Loan Management",
                "name_np": "ऋण व्यवस्थापन",
                "code": "loan_management",
                "url": "/loan-management",
                "user_type": "1",
                "icon": "loan",
            },
            {
                "name": "Loan Product",
                "name_np": "ऋण प्रोडक्‍ट",
                "code": "loan_product",
                "parent": "loan_management",
                "url": "/loan-management/loan-product",
                "user_type": "1",
            },
            {
                "name": "Individual Loan Applications",
                "name_np": "व्यक्तिगत ऋण आवेदन",
                "code": "individual_loan_applications",
                "parent": "loan_management",
                "url": "/loan-management/individual-loan-applications",
                "user_type": "1",
            },
            {
                "name": "Institutional Loan Applications",
                "name_np": "संस्थागत ऋण आवेदन",
                "code": "institutional_loan_applications",
                "parent": "loan_management",
                "url": "/loan-management/institutional-loan-applications",
                "user_type": "1",
            },
            {
                "name": "Agricultural",
                "name_np": "कृषि",
                "code": "individual_agricultural_loan",
                "parent": "individual_loan_applications",
                "url": "/loan-management/individual-agricultural-loan-applications",
                "user_type": "1",
                "is_tab": True,
            },
            {
                "name": "Non-Agricultural",
                "name_np": "गैर-कृषि",
                "code": "individual_non_agricultural_loan",
                "parent": "individual_loan_applications",
                "url": "/loan-management/individual-non-agricultural-loan-applications",
                "user_type": "1",
                "is_tab": True,
            },
            {
                "name": "Institutional Loan Applications",
                "name_np": "संस्थागत ऋण आवेदन",
                "code": "institutional_loan_applications",
                "parent": "loan_management",
                "url": "/loan-management/institutional-loan-applications",
                "user_type": "1",
            },
            {
                "name": "Agricultural",
                "name_np": "कृषि",
                "code": "institutional_agricultural_loan",
                "parent": "institutional_loan_applications",
                "url": "/loan-management/institutional-agricultural-loan-applications",
                "user_type": "1",
                "is_tab": True,
            },
            {
                "name": "Non-Agricultural",
                "name_np": "गैर-कृषि",
                "code": "institutional_non_agricultural_loan",
                "parent": "institutional_loan_applications",
                "url": "/loan-management/institutional-non-agricultural-loan-applications",
                "user_type": "1",
                "is_tab": True,
            },
            {
                "name": "Document Management",
                "name_np": "कागजात व्यवस्थापन",
                "code": "document_management",
                "url": "/document",
                "user_type": "1",
                "icon": "document",
            },
            {
                "name": "Document Title Setup",
                "name_np": "कागजात शीर्षक सेटअप",
                "code": "document_title",
                "parent": "document_management",
                "url": "/document/document-title",
                "user_type": "1",
            },
            {
                "name": "Minimum Documents Setup",
                "name_np": "न्यूनतम कागजात सेटअप",
                "code": "minimal_document",
                "parent": "document_management",
                "url": "/document/minimum-document",
                "user_type": "1",
            },
            {
                "name": "Document Group Setup",
                "name_np": "कागजात समूह सेटअप",
                "code": "document_group",
                "parent": "document_management",
                "url": "/document/document-group",
                "user_type": "1",
            },
            {
                "name": "Document Mapping",
                "name_np": "कागजात म्यापिङ",
                "code": "document_mapping",
                "parent": "document_management",
                "url": "/document/document-setup",
                "user_type": "1",
            },
            {
                "name": "Individual Document Checklist",
                "name_np": "व्यक्तिगत कागजात चेकलिस्ट सेटअप",
                "code": "individual_document_checklist",
                "parent": "document_management",
                "url": "/document/individual-document-checklist",
                "user_type": "1",
            },
            {
                "name": "Institution Document Checklist",
                "name_np": "संस्था कागजात चेकलिस्ट सेटअप",
                "code": "institution_document_checklist",
                "parent": "document_management",
                "url": "/document/institution-document-checklist",
                "user_type": "1",
            },
            {
                "name": "Reports",
                "name_np": "प्रतिवेदनहरू",
                "code": "reports",
                "url": "/reports",
                "user_type": "1",
                "icon": "reports",
            },
            {
                "name": "Summary Report",
                "name_np": "सारांश प्रतिवेदन",
                "code": "summary_report",
                "parent": "reports",
                "url": "/reports/summary-report",
                "user_type": "1",
            },
            {
                "name": "Product Wise Report",
                "name_np": "उत्पादन अनुसार प्रतिवेदन",
                "code": "product_wise_report",
                "parent": "reports",
                "url": "/reports/product-wise-report",
                "user_type": "1",
            },
            {
                "name": "Status Wise Report",
                "name_np": "स्थिति अनुसार प्रतिवेदन",
                "code": "status_wise_report",
                "parent": "reports",
                "url": "/reports/status-wise-report",
                "user_type": "1",
            },
            {
                "name": "Dashboard",
                "name_np": "ड्यासबोर्ड",
                "code": "individual_dashboard",
                "url": "/",
                "user_type": "2",
                "icon": "dashboard",
            },
            {
                "name": "Profile Setup",
                "name_np": "प्रोफाइल सेटअप",
                "code": "individual_profile",
                "url": "/user/profile",
                "user_type": "2",
                "icon": "profile",
            },
            {
                "name": "Loan Management",
                "name_np": "ऋण व्यवस्थापन",
                "code": "individual_loan_management",
                "url": "/loan-management",
                "user_type": "2",
                "icon": "loan",
            },
            {
                "name": "Loan List",
                "name_np": "ऋण सूची",
                "code": "individual_loan_list",
                "parent": "individual_loan_management",
                "url": "/loan-management/loan-list",
                "user_type": "2",
            },
            {
                "name": "My Loan Applications",
                "name_np": "मेरो ऋण आवेदनहरू",
                "code": "individual_my_loans",
                "parent": "individual_loan_management",
                "url": "/loan-management/my-loans",
                "user_type": "2",
            },
            {
                "name": "Dashboard",
                "name_np": "ड्यासबोर्ड",
                "code": "institution_dashboard",
                "url": "/",
                "user_type": "3",
                "icon": "dashboard",
            },
            {
                "name": "Profile Setup",
                "name_np": "प्रोफाइल सेटअप",
                "code": "institution_profile",
                "url": "/user/profile",
                "user_type": "3",
                "icon": "profile",
            },
            {
                "name": "Loan Management",
                "name_np": "ऋण व्यवस्थापन",
                "code": "institution_loan_management",
                "url": "/loan-management",
                "user_type": "3",
                "icon": "loan",
            },
            {
                "name": "Loan List",
                "name_np": "ऋण सूची",
                "code": "institution_loan_list",
                "parent": "institution_loan_management",
                "url": "/loan-management/loan-list",
                "user_type": "3",
            },
            {
                "name": "My Loan Applications",
                "name_np": "मेरो ऋण आवेदनहरू",
                "code": "institution_my_loans",
                "parent": "institution_loan_management",
                "url": "/loan-management/my-loans",
                "user_type": "3",
            },
        ]
        i = 0

        for menu in menus:
            i += 1
            if menu.get("parent", None):
                try:
                    parent_menu = Menu.objects.get(code=menu.get("parent"))
                except Exception:
                    parent_menu = None
            else:
                parent_menu = None
            menu, created = Menu.objects.update_or_create(
                code=menu["code"],
                defaults={
                    "parent": parent_menu,
                    "name": menu["name"],
                    "name_np": menu["name_np"],
                    "is_active": menu.get("is_active", True),
                    "order_id": menu.get("order_id", i),
                    "url": menu.get("url"),
                    "icon": menu.get("icon", ""),
                    "user_type": menu.get("user_type", "1"),
                    "is_tab": menu.get("is_tab", False),
                },
            )

            if menu.user_type == "1":
                menu.privilege.set(Privilege.objects.filter(is_active=True))

        print(".... User Menus Loaded Successfully...")
